name: Push Docker image
on:
  push:
    branches:
      - funke


jobs:
  build:

    # Permissions for GITHUB_TOKEN
    permissions:
      contents: read  # To check out repo
      packages: write # To read NPM registry and push Docker image

    uses: gunet/funke-wallet-ecosystem/.github/workflows/docker-build-push.yml@master
    secrets: inherit
    with:
      image-tag: ghcr.io/gunet/funke-wallet-frontend:latest
      docker-push: true
      dockerfile-path: ./Dockerfile
