name: Push Docker image
on:
  push:
    tags:
      - v0.*
      - v1.*
      - v2.*

jobs:
  push-front:
    permissions:
      contents: read
      packages: write

    uses: gunet/funke-wallet-ecosystem/.github/workflows/docker-build-push.yml@master
    secrets: inherit
    with:
      image-tag: ghcr.io/gunet/funke-wallet-frontend:${{ github.ref_name }}
      docker-push: true
      dockerfile-path: ./Dockerfile
